#!/usr/bin/env bash
# Install onmsg using homebrew

set -o pipefail
set -e

# Install a local homebrew if not already done
HOMEBREW="$HOME"/brew
if ! [ -d ~/brew ] ; then
    cd ~
    git clone https://github.com/Homebrew/homebrew "$HOMEBREW"
fi

export PATH="$HOMEBREW"/bin:"$PATH"

# Get an up-to-date emacs
brew tap railwaycat/emacsmacport
brew cask install emacs-mac
brew linkapps

export COLUMNS=80 # for pip, which seems to need this.

# find the User's python library location
USER_SITE_PACKAGES="$(easy_install -n --user python | grep install_dir | sed -e 's/install_dir //')"
USER_PYTHON_EXECUTABLES="$USER_SITE_PACKAGES/../../.."/bin
export PATH="$USER_PYTHON_EXECUTABLES:$PATH"

# Get an up-to-date pip
if ! [ "$(which pip)" ] ; then
    easy_install --user pip
else
    pip install --upgrade --user --install-option="--prefix=" pip
fi

# Use it to get an up-to-date imaplib2
CELLAR_IMAPLIB2="$(brew --cellar)/imaplib2-head"
CELLAR_IMAPLIB2_PREFIX="$CELLAR_IMAPLIB2/$(date '+%Y%m%d')"
if [ -d "$CELLAR_IMAPLIB2" ] ; then
    brew rm imaplib2-head
fi
BUILD=$(mktemp -d)
pip install --upgrade \
    --user \
    --src="$CELLAR_IMAPLIB2_PREFIX/src" \
    --build="$BUILD" \
    --install-option="--prefix=$CELLAR_IMAPLIB2_PREFIX" \
    --editable "git://git.code.sf.net/p/imaplib2/code#egg=imaplib2"
brew link imaplib2-head
rmdir "$BUILD"

# Install stunnel, so leafnode can access gmane inside Apple's firewall
brew install stunnel

brew install dovecot --with-clucene --with-stemmer
brew install leafnode
brew install isync
mkdir -p "$HOME"/Library/Data/mbsync

# Create a disk image and mount point for leafnode's news spool.  Last
# we checked, its ordinary format soaks up way too many actual inodes.
LEAFNODE_IMAGE="$HOME"/Library/Data/leafnode.sparsebundle
LEAFNODE_DIR="$HOME"/Library/Data/leafnode
if ! [ -e "$LEAFNODE_IMAGE" ]; then
    hdiutil create -size 10g "$LEAFNODE_IMAGE" -fs "JHFS+X" -uid 99 -gid 99
fi
hdiutil attach "$LEAFNODE_IMAGE" -mountpoint "$LEAFNODE_DIR" -nobrowse -noautofsck

# Get syncthing for syncing Gnus files.
brew cask install syncthing
brew install syncthing-inotify

